apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  index.html: |
    <html>
    <head>
      <title>Devops 2026 !!!!!!!</title>
    </head>
    <body>
      <h1>Welcome to Devops World !!!!!!!!!</h1>
      <p>Happy place for Cloud and DevOps </p>
    </body>
    </html>
